server:
  port: 50001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/element-db
    username: root
    password: elbouchouki

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone:
    fetch-registry: false
    register-with-eureka: false