server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/example-db
    username: example-user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/