server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globals:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service
      - url: /utilisateur-service/docs
        name: Utilisateur Service
        primaryName: Utilisateur Service
      - url: /departement-service/docs
        name: Departement Service
        primaryName: Departement Service
      - url: /filiere-service/docs
        name: Filiere Service
        primaryName: Filiere Service
      - url: /semestre-service/docs
        name: Semestre Service
        primaryName: Semestre Service
      - url: /module-service/docs
        name: Module Service
        primaryName: Module Service
      - url: /element-service/docs
        name: Element Service
        primaryName: Element Service
      - url: /deliberation-service/docs
        name: Deliberation Service
        primaryName: Deliberation Service



logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionRouteLocator: TRACE

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka